type Query {
  user(id: String): User
  users: [User]
  word(id: String): Word
  words: [Word]
  game(id: String): Game
  games: [Game]
  game_user(id: String): GameUser
  game_users: [GameUser]
}

type Word {
  id: ID!
  title: String
}

type User {
  id: ID!
  name: String!
  email: String!
  games: [Game]
}

type GameUser {
  id: ID!
  user: User!
  game: Game!
  select_word: [SelectWord]!
}

type Game {
  id: ID!
  game_users: [GameUser]
}

type SelectWord {
  id: ID!
  user: User!
  word: Word!
}
